### ISSUE TITLE
Scalar can't contain colon (":")

### ISSUE THREAD

**Issue by robert-zaremba** [kylelemons/go-gypsy#18]
I want to have a string value, which contains ":" inside.
The following yaml:

```
addr:  localhost:8000
```

is interpreted as {"addr": {"localhost": 8000}}. Whereas 

```
addr:  "localhost:8000"
```

as {"addr": "\"localhost:8000\""}.
I need {"addr": "localhost:8000"}

code: http://play.golang.org/p/51uwiNYH8N

**Comment by kylelemons** [comment]
This appears to have been fixed already, as the playground link shows

> value: localhost:8000, type: string
