### ISSUE TITLE
Issue in termination of multiline string with indentation 

### ISSUE THREAD

**Issue by ihtkas** [kylelemons/go-gypsy#24]
Consider the below exmaple,

```
Load:
    - Testts.add:
        - Name: |
            xline1
            xline2
        - Name: |
            yline1
            yline2
```

I have used two multiline string values. When the above string is parsed, the first multi line string is not terminated after the indentation level is reduced ie, "xline1\nxline2\n- Name: |\nyline1\nyline2" is formed as single string and assigned as value to Name key and only one item is added in the list (for key Testts.add).

**Comment by sprabhakaran** [comment]
@kylelemons   I too faced same problem.  @Ihtkas

**Comment by Gregory-Ledray** [comment]
The README says multi-line strings aren't supported.

> // BUG(kevlar): Multi-line strings are currently not supported.

**Comment by ihtkas** [comment]
@Gregory-Ledray Thanks for pointing this.
